### ISSUE TITLE
Sopped working after HA 2023.5.0 update

### ISSUE THREAD

**Issue by jusii** [DotEfekts/ElectroluxClimateComponent#2]
I knew this was coming due to some changes in HA, so it stopped working after update today:

Logger: homeassistant.config_entries
Source: custom_components/electrolux_climate/__init__.py:10
Integration: Electrolux Climate
First occurred: 9:53:00 AM (1 occurrences)
Last logged: 9:53:00 AM

Error setting up entry Electrolux Climate for electrolux_climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/electrolux_climate/__init__.py", line 10, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by DotEfekts** [comment]
Fixed in fa632b95a6e5050c063b57512640b952db29f7e4

**Comment by stevesmate4503** [comment]
2025.1.0 has now also got this same issue
