### ISSUE TITLE
Temperature range and 8 degree mode

### ISSUE THREAD

**Issue by EagleStClair** [DotEfekts/ElectroluxClimateComponent#4]
This works very well with my Electrolux heat pump, but the available temp.range in home assistant goes to 17 degrees but in Electrolux app it goes down to 16.

Also, in the Electrolux app there is a 8 degree mode (which actually sets the pump to 10 degrees) can that be added to the integration?

**Comment by DotEfekts** [comment]
Hi,

The 8 degree heat mode is actually part of the [Broadlink extension](https://github.com/DotEfekts/ElectroluxClimateComponent/blob/master/custom_components/electrolux_climate/electrolux.py) I wrote, however I don't believe HomeAssistant supports custom modes for the climate component. I have very limited experience with Python and HA so I'm not sure how to add configuration for the temperature range. You could fork the project and update the `MIN_TEMP` [here](https://github.com/DotEfekts/ElectroluxClimateComponent/blob/master/custom_components/electrolux_climate/electrolux.py#L12) and [here](https://github.com/DotEfekts/ElectroluxClimateComponent/blob/master/custom_components/electrolux_climate/const.py#L11).

**Comment by EagleStClair** [comment]
Ah I see, yeah you are right. It seems from [here](https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes) that only built-in HVAC modes are allowed.
So either utilize an unused mode like HEAT_COOL for HEAT_8 even if the naming will mismatch, or use a preset like AWAY.

I could only wish for limited experience, mine are non existent. But maybe some day if I feel brave

**Comment by EagleStClair** [comment]
I made a fork and modified the elux mode HEAT_8 to match hvac mode HEAT_COOL. Also adjusted min temp range to 16 degrees. Works fine for me so I created a pull request #5 
Not sure if it is useful to anyone else and should be merged or not, really don't know how to behave in the github and open source world.

**Comment by DotEfekts** [comment]
Hi, the `HEAT_8` change has been merged and I've just pushed an update to allow configuration of the temperature range. You'll need to remove and readd the device to configure the temperature.
