### ISSUE TITLE
Support LED turn off

### ISSUE THREAD

**Issue by Elliottmonaghan** [DotEfekts/ElectroluxClimateComponent#8]
Looks like it's in the files but can't seem to find a way to integrate LED control within home assistant climate cards or even use a switch. Would be favourable as turning the LED off also turns the air conditioner onto a silent mode and allows adjustments without an audible beep for each setting.

**Comment by DotEfekts** [comment]
I've just pushed an update to add it as a separate switch entity (no way to add it to the climate entity as far as I know)

**Comment by Elliottmonaghan** [comment]
Mate you're a legend!
