### ISSUE TITLE
Issue with HA 2024.8.0> and Broadlink

### ISSUE THREAD

**Issue by talondnb** [DotEfekts/ElectroluxClimateComponent#9]
Hi,

Ref: https://github.com/home-assistant/core/issues/123326#issuecomment-2522920476

I'm unsure if this is related, but there may be some issue with this custom component when running HA 2024.8.0 and above (problem started at this version, see above reference link).

The issue still remains for me; any time a reboot of HA is done, the broadlink component fails to start unless another reboot is done. I noticed that this custom component [manifest.json](https://github.com/DotEfekts/ElectroluxClimateComponent/blob/master/custom_components/electrolux_climate/manifest.json) uses broadlink 0.18.2, could this be the cause? According to [here](https://github.com/home-assistant/core/blob/dev/homeassistant/components/broadlink/manifest.json), 0.19.0 is the latest?

I have no idea by the way, just a while stab in the dark to try and overcome this niggling issue. 👍

Any assistance appreciated!

**Comment by Deanosim** [comment]
Okay so I've done some testing and made my own fork to test if the fix would be as simple as I thought, all I've done it changed the broadlink version in the manifest and requirements.txt to 0.19.0 and then removed the old component from HACS to test my fork, but it seems to fix the problem.

**Comment by Deanosim** [comment]
@talondnb I tested trying to enable SmartIR and discovered it's also out of date, and looks like theirs a bunch of open issues of people complaining about the same problem. Just thought I'd let you know that it also needs updating.

**Comment by talondnb** [comment]
> Okay so I've done some testing and made my own fork to test if the fix would be as simple as I thought, all I've done it changed the broadlink version in the manifest and requirements.txt to 0.19.0 and then removed the old component from HACS to test my fork, but it seems to fix the problem.

Awesome, thanks so much for testing the suspicion! Are you able to do a pull request? Or perhaps we wait for @DotEfekts to chime in?

**Comment by DotEfekts** [comment]
Merge accepted, thanks!
